dist: xenial
language: go

arch:
  - amd64
  - i386
  - arm64
  - arm32
  
go:
- "1.12"

git:
  depth: 1

script:
  - unset GO111MODULE # Needed?
  - go build cmd/appimagetool/appimagetool.go
  - strip ./appimagetool
  - ls -lh ./appimagetool
  - ./appimagetool
  - go build cmd/appimaged
  - strip ./appimaged
  - ls -lh ./appimaged
  - ./appimaged &
  - sleep 10
  - killall appimaged

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh appimagetool appimaged
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

#cache:
#  directories:
#    - $HOME/.cache/go-build
#    - $HOME/gopath/src
