dist: xenial
language: go

go:
- "1.12"

git:
  depth: 1

script:
  - go build cmd/appimagetool/appimagetool.go
  - strip ./appimagetool
  - ls -lh ./appimagetool
  - ./appimagetool
  - go cmd/appimaged/appimaged.go
  - strip ./appimaged
  - ls -lh ./appimaged
  - ./appimaged &
  - sleep 10
  - killall appimaged
