dist: xenial
language: none

arch:
  - amd64
  - arm64

git:
  depth: 1

script:
  - unset GOARCH GOBIN GOEXE GOHOSTARCH GOHOSTOS GOOS GORACE GOROOT GOTOOLDIR CC GOGCCFLAGS CGO_ENABLED
  - export GOPATH=$HOME/go
  - export COMMIT="${TRAVIS_BUILD_NUMBER}" # "${TRAVIS_JOB_WEB_URL} on $(date +'%Y-%m-%d_%T')"
  - export VERSION=$TRAVIS_BUILD_NUMBER
  - if [ "aarch64" == "$TRAVIS_ARCH" ] ; then export ARCH=arm64 ; fi
  - if [ "amd64" == "$TRAVIS_ARCH" ] ; then export ARCH=amd64 ; fi
  - wget -q https://dl.google.com/go/go1.13.4.linux-$ARCH.tar.gz
  - sudo tar -C /usr/local -xzf go*.tar.gz
  - export PATH=/usr/local/go/bin:$PATH
  - if [ $(go env GOHOSTARCH) == "amd64" ] ; then sudo apt-get -y install gcc-multilib g++-multilib ; fi
  - if [ $(go env GOHOSTARCH) == "amd64" ] ; then wget -c -q https://github.com/upx/upx/releases/download/v3.95/upx-3.95-amd64_linux.tar.xz ; fi
  - if [ $(go env GOHOSTARCH) == "arm64" ] ; then sudo apt-get -y install gcc-arm-linux-gnueabi ; fi
  - if [ $(go env GOHOSTARCH) == "arm64" ] ; then wget -c -q https://github.com/upx/upx/releases/download/v3.95/upx-3.95-arm64_linux.tar.xz ; fi
  - tar xf upx-*_linux.tar.xz
  - export PATH=$(readlink -f upx-*_linux/):$PATH
  # export GO111MODULE=off
  # appimagetool
  - go get github.com/probonopd/appimage/src/appimagetool
  - go build -trimpath -ldflags="-s -w -X main.commit=$COMMIT" github.com/probonopd/appimage/src/appimagetool
  - upx -9 appimagetool
  - mv ./appimagetool appimagetool-$(go env GOHOSTARCH)
  - if [ $(go env GOHOSTARCH) == "amd64" ] ; then env CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -trimpath -ldflags="-s -w -X main.commit=$COMMIT" github.com/probonopd/appimage/src/appimagetool ; fi
  - if [ $(go env GOHOSTARCH) == "amd64" ] ; then upx -9 ./appimagetool ; fi
  - if [ $(go env GOHOSTARCH) == "amd64" ] ; then mv ./appimagetool appimagetool-386 ; fi
  - if [ $(go env GOHOSTARCH) == "arm64" ] ; then env CC=arm-linux-gnueabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=5 go build -trimpath -ldflags="-s -w -X main.commit=$COMMIT" github.com/probonopd/appimage/src/appimagetool ; fi
  - if [ $(go env GOHOSTARCH) == "arm64" ] ; then upx -9 ./appimagetool ; fi
  - if [ $(go env GOHOSTARCH) == "arm64" ] ; then mv ./appimagetool appimagetool-arm ; fi
  # appimaged
  - go get github.com/probonopd/appimage/src/appimaged
  - go build -trimpath -ldflags="-s -w -X main.commit=$COMMIT" github.com/probonopd/appimage/src/appimaged
  - upx -9 appimaged
  - mv ./appimaged appimaged-$(go env GOHOSTARCH)
  - if [ $(go env GOHOSTARCH) == "amd64" ] ; then env CGO_ENABLED=1 GOOS=linux GOARCH=386 go build -trimpath -ldflags="-s -w -X main.commit=$COMMIT" github.com/probonopd/appimage/src/appimaged ; fi
  - if [ $(go env GOHOSTARCH) == "amd64" ] ; then upx -9 ./appimaged ; fi
  - if [ $(go env GOHOSTARCH) == "amd64" ] ; then mv ./appimaged appimaged-386 ; fi
  - if [ $(go env GOHOSTARCH) == "arm64" ] ; then env CC=arm-linux-gnueabi-gcc CGO_ENABLED=1 GOOS=linux GOARCH=arm GOARM=5 go build -trimpath -ldflags="-s -w -X main.commit=$COMMIT" github.com/probonopd/appimage/src/appimaged ; fi
  - if [ $(go env GOHOSTARCH) == "arm64" ] ; then upx -9 ./appimaged ; fi
  - if [ $(go env GOHOSTARCH) == "arm64" ] ; then mv ./appimaged appimaged-arm ; fi
  # Eat our own dogfood, use appimagetool to make AppImages
  - |
    if [ $(go env GOHOSTARCH) == "amd64" ] ; then
    # appimagetool
    mkdir -p appimagetool.AppDir/usr/bin
    ( cd appimagetool.AppDir/usr/bin/ ; wget -c https://github.com/probonopd/static-tools/releases/download/continuous/desktop-file-validate )
    ( cd appimagetool.AppDir/usr/bin/ ; wget -c https://github.com/probonopd/static-tools/releases/download/continuous/mksquashfs )
    ( cd appimagetool.AppDir/usr/bin/ ; wget -c https://github.com/AppImage/AppImageKit/releases/download/continuous/runtime-x86_64 )
    chmod +x appimagetool.AppDir/usr/bin/*
    cp appimagetool-amd64 appimagetool.AppDir/usr/bin/appimagetool
    ( cd appimagetool.AppDir/ ; ln -s usr/bin/appimagetool AppRun)
    cp data/appimage.png appimagetool.AppDir/
    cat > appimagetool.AppDir/appimagetool.desktop <<\EOF
    [Desktop Entry]
    Type=Application
    Name=appimagetool
    Exec=appimagetool
    Comment=Tool to generate AppImages from AppDirs
    Icon=appimage
    Categories=Development;
    Terminal=true
    EOF
    PATH=./appimagetool.AppDir/usr/bin/:$PATH ARCH=x86_64 appimagetool ./appimagetool.AppDir
    fi
  # Recursively eat our own dogfood, use the appimagetool AppImage to make AppImages
  - |
    if [ $(go env GOHOSTARCH) == "amd64" ] ; then
    # appimaged
    mkdir -p appimaged.AppDir/usr/bin
    ( cd appimaged.AppDir/usr/bin/ ; wget -c https://github.com/probonopd/static-tools/releases/download/continuous/bsdtar )
    ( cd appimaged.AppDir/usr/bin/ ; wget -c https://github.com/probonopd/static-tools/releases/download/continuous/unsquashfs )
    chmod +x appimaged.AppDir/usr/bin/*
    cp appimaged-amd64 appimaged.AppDir/usr/bin/appimaged
    ( cd appimaged.AppDir/ ; ln -s usr/bin/appimaged AppRun)
    cp data/appimage.png appimaged.AppDir/
    cat > appimaged.AppDir/appimaged.desktop <<\EOF
    [Desktop Entry]
    Type=Application
    Name=appimaged
    Exec=appimaged
    Comment=Optional daemon that integrates AppImages into the system
    Icon=appimage
    Categories=Utility;
    Terminal=true
    NoDisplay=true
    EOF
    ./appimagetool-*-x86_64.AppImage ./appimaged.AppDir
    fi

after_success:
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh appimaged-* appimagetool-* *.AppImage* || true

branches:
  except:
    # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/

#cache:
#  directories:
#    - $HOME/gopath/src
